version: "3"

services:
  booker:
    container_name: booker
    build: .
    ports:
      - "8080:8080"
    environment:
      - IS_PREPARE_AVAILABILITY_REQUIRED=true
      - SERVER_PORT=8080
    command:
      - "./app"